import{createClient}from'https://esm.sh/@supabase/supabase-js@2';
export const sb=createClient('https://rxjgnaldzryzkyoxgrle.supabase.co','eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4amduYWxkenJ5emt5b3hncmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAwNDYzNzUsImV4cCI6MjEwNTYyMjM3NX0.9YFteJnn1SH4byYmw_EvHWMT4fV8cedz6xmgHUXcJMs');
export const $=s=>document.querySelector(s);export const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
export const date=s=>s?new Date(s).toLocaleDateString('zh-CN',{year:'numeric',month:'short',day:'numeric'}):'未发布';
export const isoDate=s=>s?new Date(s).toISOString().slice(0,10).replaceAll('-','.'):'未发布';
export const category=p=>p.category?.name||p.category||'随笔';export const reading=p=>p.read_time_minutes||Math.max(1,Math.ceil((p.content||'').length/220));export const plain=s=>String(s||'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();export const safeHTML=(html,text)=>html||`<p>${esc(text||'').replace(/\n/g,'<br>')}</p>`;
export function card(p,i=0){return `<article class="item"><a href="post.html?slug=${encodeURIComponent(p.slug)}" aria-label="阅读：${esc(p.title)}">${p.cover_url?`<img class="item-media" loading="lazy" decoding="async" src="${esc(p.cover_url)}" alt="${esc(p.title)}">`:'<div class="item-media" aria-hidden="true"></div>'}</a><div><div class="meta"><span class="tag">${esc(category(p))}</span><time datetime="${esc(p.published_at||p.created_at||'')}">${isoDate(p.published_at||p.created_at)}</time><span>${String(reading(p)).padStart(2,'0')} MIN</span></div><h2><a href="post.html?slug=${encodeURIComponent(p.slug)}">${esc(p.title)}</a></h2><p>${esc(p.excerpt||plain(p.content).slice(0,150)||'打开文章阅读正文。')}</p></div></article>`}
export async function published(){const r=await sb.from('posts').select('id,title,slug,excerpt,content,content_html,cover_url,status,featured,read_time_minutes,published_at,created_at,updated_at,category:categories(name,slug)').eq('status','published').order('published_at',{ascending:false}).limit(100);if(r.error)throw r.error;return r.data||[]}
export function shell(active='文章'){return `<div class="shell"><header class="topbar"><a class="brand" href="index.html" aria-label="reincarnation.log 首页"><i></i>reincarnation.log</a><nav class="nav" aria-label="主导航"><a class="${active==='首页'?'active':''}" href="index.html">INDEX</a><a class="${active==='文章'?'active':''}" href="archive.html">LOG</a><a class="${active==='主题'?'active':''}" href="topics.html">TOPICS</a><a class="${active==='归档'?'active':''}" href="archive.html">ARCHIVE</a><a class="${active==='关于'?'active':''}" href="about.html">ABOUT</a></nav></header><aside class="global-sidebar" aria-label="档案侧边栏"><div class="side-kicker">PERSONAL DIGITAL ARCHIVE</div><div class="side-year">2026</div><a class="${active==='首页'?'active':''}" href="index.html"><span>INDEX</span><span>↗</span></a><a class="${active==='文章'?'active':''}" href="archive.html"><span>LOG / ENTRIES</span><span>↗</span></a><a class="${active==='主题'?'active':''}" href="topics.html"><span>TOPICS</span><span>↗</span></a><a class="${active==='归档'?'active':''}" href="archive.html"><span>ARCHIVE</span><span>↗</span></a><a class="${active==='关于'?'active':''}" href="about.html"><span>ABOUT</span><span>↗</span></a><div class="side-status"><i></i> SUPABASE ONLINE</div><p class="side-note">慢一点写，清楚一点读。保留上下文，也允许改变主意。</p></aside>`}
export function footer(){return `<footer class="footer"><span>© 2026 reincarnation.log · ARCHIVE 3.0</span><span><a href="guestbook.html">留言板</a> · <a href="friends.html">友链</a> · <a href="feed.xml">RSS</a> · <a href="admin.html">管理</a></span></footer></div>`}
export function bindLightbox(){const box=$('#lightbox'),preview=$('#lightbox img');document.querySelectorAll('.post-body img,.post-cover').forEach((img,i)=>{img.tabIndex=0;img.setAttribute('role','button');img.setAttribute('aria-label','放大图片');const open=()=>{preview.src=img.currentSrc||img.src;preview.alt=img.alt||'图片预览';box.classList.add('open');box.setAttribute('aria-hidden','false')};img.addEventListener('click',open);img.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')open()})});const close=()=>{box?.classList.remove('open');box?.setAttribute('aria-hidden','true')};box?.addEventListener('click',e=>{if(e.target===box||e.target.closest('button'))close()});document.addEventListener('keydown',e=>e.key==='Escape'&&close())}
